# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDF Merger.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 349)
        self.FolderSelector = QtWidgets.QToolButton(Dialog)
        self.FolderSelector.setGeometry(QtCore.QRect(580, 50, 29, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FolderSelector.setFont(font)
        self.FolderSelector.setObjectName("FolderSelector")
        self.Folder = QtWidgets.QLineEdit(Dialog)
        self.Folder.setGeometry(QtCore.QRect(50, 50, 521, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Folder.setFont(font)
        self.Folder.setObjectName("Folder")
        self.OutputBox = QtWidgets.QLineEdit(Dialog)
        self.OutputBox.setGeometry(QtCore.QRect(50, 200, 551, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OutputBox.setFont(font)
        self.OutputBox.setObjectName("OutputBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 59, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 71, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.OpenFolder = QtWidgets.QPushButton(Dialog)
        self.OpenFolder.setGeometry(QtCore.QRect(150, 240, 111, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OpenFolder.setFont(font)
        self.OpenFolder.setObjectName("OpenFolder")
        self.OpenFile = QtWidgets.QPushButton(Dialog)
        self.OpenFile.setGeometry(QtCore.QRect(50, 240, 91, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.OpenFile.setFont(font)
        self.OpenFile.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.OpenFile.setCheckable(False)
        self.OpenFile.setObjectName("OpenFile")
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setGeometry(QtCore.QRect(385, 240, 111, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OK.setFont(font)
        self.OK.setObjectName("OK")
        self.ClearFields = QtWidgets.QPushButton(Dialog)
        self.ClearFields.setGeometry(QtCore.QRect(510, 240, 91, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ClearFields.setFont(font)
        self.ClearFields.setObjectName("ClearFields")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(50, 280, 551, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.DONE = QtWidgets.QLabel(Dialog)
        self.DONE.setGeometry(QtCore.QRect(270, 240, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DONE.setFont(font)
        self.DONE.setText("")
        self.DONE.setAlignment(QtCore.Qt.AlignCenter)
        self.DONE.setObjectName("DONE")
        self.mergePdfs = QtWidgets.QRadioButton(Dialog)
        self.mergePdfs.setGeometry(QtCore.QRect(220, 100, 99, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mergePdfs.setFont(font)
        self.mergePdfs.setObjectName("mergePdfs")
        self.action = QtWidgets.QButtonGroup(Dialog)
        self.action.setObjectName("action")
        self.action.addButton(self.mergePdfs)
        self.frontCover = QtWidgets.QRadioButton(Dialog)
        self.frontCover.setGeometry(QtCore.QRect(440, 121, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frontCover.setFont(font)
        self.frontCover.setObjectName("frontCover")
        self.action.addButton(self.frontCover)
        self.backCover = QtWidgets.QRadioButton(Dialog)
        self.backCover.setGeometry(QtCore.QRect(440, 100, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backCover.setFont(font)
        self.backCover.setObjectName("backCover")
        self.action.addButton(self.backCover)
        self.README = QtWidgets.QPushButton(Dialog)
        self.README.setGeometry(QtCore.QRect(50, 100, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.README.setFont(font)
        self.README.setObjectName("README")
        self.filterPages = QtWidgets.QRadioButton(Dialog)
        self.filterPages.setGeometry(QtCore.QRect(220, 120, 196, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filterPages.setFont(font)
        self.filterPages.setAutoFillBackground(False)
        self.filterPages.setObjectName("filterPages")
        self.action.addButton(self.filterPages)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.backCover, self.frontCover)
        Dialog.setTabOrder(self.frontCover, self.mergePdfs)
        Dialog.setTabOrder(self.mergePdfs, self.filterPages)
        Dialog.setTabOrder(self.filterPages, self.README)
        Dialog.setTabOrder(self.README, self.Folder)
        Dialog.setTabOrder(self.Folder, self.FolderSelector)
        Dialog.setTabOrder(self.FolderSelector, self.ClearFields)
        Dialog.setTabOrder(self.ClearFields, self.OK)
        Dialog.setTabOrder(self.OK, self.OpenFolder)
        Dialog.setTabOrder(self.OpenFolder, self.OpenFile)
        Dialog.setTabOrder(self.OpenFile, self.OutputBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.FolderSelector.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "INPUT"))
        self.label_5.setText(_translate("Dialog", "OUTPUT"))
        self.OpenFolder.setText(_translate("Dialog", "Open Folder"))
        self.OpenFile.setText(_translate("Dialog", "Open File"))
        self.OK.setText(_translate("Dialog", "OK"))
        self.ClearFields.setText(_translate("Dialog", "Clear Fields"))
        self.mergePdfs.setText(_translate("Dialog", "Merge PDFs"))
        self.frontCover.setText(_translate("Dialog", "Extract Front Cover"))
        self.backCover.setText(_translate("Dialog", "Extract Back Cover"))
        self.README.setText(_translate("Dialog", "README"))
        self.filterPages.setText(_translate("Dialog", "Remove first and last pages"))
