# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDF Merger.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 383)
        Dialog.setMinimumSize(QtCore.QSize(490, 383))
        Dialog.setMaximumSize(QtCore.QSize(490, 383))
        self.FolderSelector = QtWidgets.QToolButton(Dialog)
        self.FolderSelector.setGeometry(QtCore.QRect(440, 70, 29, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FolderSelector.setFont(font)
        self.FolderSelector.setObjectName("FolderSelector")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 471, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Folder = QtWidgets.QLineEdit(Dialog)
        self.Folder.setGeometry(QtCore.QRect(10, 70, 421, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Folder.setFont(font)
        self.Folder.setObjectName("Folder")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 391, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 471, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.OutputBox = QtWidgets.QLineEdit(Dialog)
        self.OutputBox.setGeometry(QtCore.QRect(10, 250, 471, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OutputBox.setFont(font)
        self.OutputBox.setObjectName("OutputBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 59, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 71, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.OpenFolder = QtWidgets.QPushButton(Dialog)
        self.OpenFolder.setGeometry(QtCore.QRect(110, 290, 91, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OpenFolder.setFont(font)
        self.OpenFolder.setObjectName("OpenFolder")
        self.OpenFile = QtWidgets.QPushButton(Dialog)
        self.OpenFile.setGeometry(QtCore.QRect(10, 290, 91, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.OpenFile.setFont(font)
        self.OpenFile.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.OpenFile.setCheckable(False)
        self.OpenFile.setObjectName("OpenFile")
        self.Merger = QtWidgets.QPushButton(Dialog)
        self.Merger.setGeometry(QtCore.QRect(300, 290, 86, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Merger.setFont(font)
        self.Merger.setObjectName("Merger")
        self.ClearFields = QtWidgets.QPushButton(Dialog)
        self.ClearFields.setGeometry(QtCore.QRect(390, 290, 86, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ClearFields.setFont(font)
        self.ClearFields.setObjectName("ClearFields")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 340, 471, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.DONE = QtWidgets.QLabel(Dialog)
        self.DONE.setGeometry(QtCore.QRect(200, 297, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DONE.setFont(font)
        self.DONE.setText("")
        self.DONE.setAlignment(QtCore.Qt.AlignCenter)
        self.DONE.setObjectName("DONE")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.FolderSelector.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Select the folder that contains the PDF documents you would like to merge.</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">NOTE: This will select and merge all PDF documents in that folder.</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Next select an output name for your merged PDF. It will be saved in the same folder you previously selected.</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "INPUT"))
        self.label_5.setText(_translate("Dialog", "OUTPUT"))
        self.OpenFolder.setText(_translate("Dialog", "Open Folder"))
        self.OpenFile.setText(_translate("Dialog", "Open File"))
        self.Merger.setText(_translate("Dialog", "Merge"))
        self.ClearFields.setText(_translate("Dialog", "Clear Fields"))

